apiVersion: v1
kind: replicaset
metadata:
  name: large-replicaset
  labels:
    app: capacity
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capacity
  template:
    metadata:
      name: large-pod
      labels:
        app: capacity
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google-samples/gb-frontend:v4
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 2000m
            memory: 12Gi
          requests:
            cpu: 1000m
            memory: 6Gi
      restartPolicy: "OnFailure"
      dnsPolicy: "Default"
